package src.Spaces;

public enum SpaceType {
    COURT,
    AUDITORIUM,
    BASIC_ROOM,
    SLIDES_ROOM,
    COMPUTER_ROOM,
    PHYSICS_LABORATORY,
    CHEMISTRY_LABORATORY,
    ELETRONICS_LABORATORY
}
